(deffacts dishes
  (dish (ID 1)(name "test") (cuisine "chinese") (is-vegetarian "TRUE") (fat-level "low fat")(calorie-level "low calorie") (fiber-level "low fiber") (spicy-level "no spicy") (sour-level "no sour") (sweet-level "no sweet") (salty-level "no salty") (stars -1))
  (dish (ID 2)(name "test") (cuisine "chinese") (is-vegetarian "FALSE") (fat-level "normal fat")(calorie-level "normal calorie") (fiber-level "normal fiber") (spicy-level "a bit spicy") (sour-level "a bit sour") (sweet-level "a bit sweet") (salty-level "a bit salty") (stars -1))
  (dish (ID 3)(name "test") (cuisine "chinese") (is-vegetarian "TRUE") (fat-level "low fat")(calorie-level "low calorie") (fiber-level "low fiber") (spicy-level "no spicy") (sour-level "a bit sour") (sweet-level "a bit sweet") (salty-level "no salty") (stars -1))
  (dish (ID 4)(name "test") (cuisine "chinese") (is-vegetarian "FALSE") (fat-level "normal fat")(calorie-level "normal calorie") (fiber-level "normal fiber") (spicy-level "a bit spicy") (sour-level "a bit sour") (sweet-level "a bit sweet") (salty-level "a bit salty") (stars -1))
  (dish (ID 5)(name "test") (cuisine "chinese") (is-vegetarian "TRUE") (fat-level "low fat")(calorie-level "low calorie") (fiber-level "low fiber") (spicy-level "no spicy") (sour-level "no sour") (sweet-level "no sweet") (salty-level "no salty") (stars -1))
  (dish (ID 6)(name "test") (cuisine "chinese") (is-vegetarian "TRUE") (fat-level "low fat")(calorie-level "low calorie") (fiber-level "low fiber") (spicy-level "no spicy") (sour-level "no sour") (sweet-level "no sweet") (salty-level "no salty") (stars -1))
  (dish (ID 7)(name "test") (cuisine "chinese") (is-vegetarian "FALSE") (fat-level "normal fat")(calorie-level "normal calorie") (fiber-level "normal fiber") (spicy-level "a bit spicy") (sour-level "a bit sour") (sweet-level "a bit sweet") (salty-level "a bit salty") (stars -1))
  (dish (ID 8)(name "test image") (cuisine "vietnamese") (is-vegetarian "TRUE") (fat-level "low fat")(calorie-level "low calorie") (fiber-level "low fiber") (spicy-level "no spicy") (sour-level "no sour") (sweet-level "no sweet") (salty-level "no salty") (stars -1)))
